theme = "curzon"

[editor]
completion-timeout = 5
cursorline = true
line-number = "relative"

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.normal]
A-j = "goto_word"
A-k = "file_picker_in_current_buffer_directory"
A-s = ":w"
C-s = ":w"
Cmd-s = ":w"

[keys.insert]
A-j = "normal_mode"
A-s = [":w", "normal_mode"]
C-s = [":w", "normal_mode"]
Cmd-s = [":w", "normal_mode"]
